export const transactions = [
  {
    id: 1,
    category: "Income",
    date: "Nov 02, 2021",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, suscipit distinctio? Libero consequuntur rem inventore alias animi similique qui quae!",
    money: "25000",
    gain: true,
  },
  {
    id: 2,
    category: "Transport",
    date: "Oct 31, 2021",
    desc: "Lorem ipsum dolor sit amet Libero consequuntur rem inventore alias animi similique qui quae!",
    money: "854",
    gain: false,
  },
  {
    id: 3,
    category: "Food and Drinks",
    date: "Oct 27, 2021",
    desc: "rem inventore alias animi similique qui quae!",
    money: "600",
    gain: false,
  },
  {
    id: 4,
    category: "Food and Drinks",
    date: "Oct 22, 2021",
    desc: "rem inventore alias animi similique nventore alias animi similique qui quae!",
    money: "230",
    gain: false,
  },
  {
    id: 5,
    category: "Transport",
    date: "Oct 18, 2021",
    desc: "rem inventor einventor einventore alias animi similique nventore alias animi similique qui quae!",
    money: "330",
    gain: false,
  },
  {
    id: 6,
    category: "Food and Drinks",
    date: "Oct 14, 2021",
    desc: "rem nventore alias animi similique qui quae!",
    money: "2000",
    gain: false,
  },
  {
    id: 7,
    category: "Transport",
    date: "Oct 10, 2021",
    desc: "rem em nventore alias an similique qui quae!",
    money: "545",
    gain: false,
  },
  {
    id: 8,
    category: "Trading",
    date: "Oct 08, 2021",
    desc: "--",
    money: "2800",
    gain: true,
  },
  {
    id: 9,
    category: "Food and Drinks",
    date: "Oct 07, 2021",
    desc: "m nventore alias animi similique quim nventore alias animi similique qui",
    money: "234",
    gain: false,
  },
  {
    id: 10,
    category: "Side Income",
    date: "Oct 05, 2021",
    desc: "m nventore similique qui",
    money: "234",
    gain: false,
  },
  {
    id: 11,
    category: "Groceries",
    date: "Oct 03, 2021",
    desc: "--",
    money: "7532",
    gain: false,
  },
  {
    id: 12,
    category: "Income",
    date: "Oct 02, 2021",
    desc: "m nventore alias animi similique quim nventore alias animi similique qui",
    money: "23000",
    gain: false,
  },
];
